apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cheeky.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cheeky.name" . }}
    helm.sh/chart: {{ include "cheeky.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.websocket.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cheeky.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cheeky.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.websocket.image.repository }}:{{ .Values.websocket.image.tag }}"
          imagePullPolicy: {{ .Values.websocket.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ping
              port: http
          resources:
            {{- toYaml .Values.websocket.resources | nindent 12 }}
      {{- with .Values.websocket.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.websocket.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.websocket.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
